services:
  - type: web
    name: paletteai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: HF_API_TOKEN
        fromGroup: paletteai-secrets
      - key: HF_MODEL
        value: mistralai/Mistral-7B-Instruct-v0.3
      - key: HF_PROVIDER
        value: novita
      - key: PYTHON_VERSION
        value: 3.10.8