import React from 'react';
import { Link } from 'react-router-dom';

const EXAMPLES = [
  {
    business: "Tech Startup",
    industry: "Technology",
    style: "Modern",
    palette: [
      { name: "Sky Blue", hex: "#3A86FF" },
      { name: "Royal Purple", hex: "#8338EC" },
      { name: "Crimson Red", hex: "#FF006E" },
      { name: "Ivory", hex: "#F8F9FA" },
      { name: "Charcoal", hex: "#212529" },
      { name: "Turquoise", hex: "#06B6D4" },
      { name: "Slate Gray", hex: "#94A3B8" },
      { name: "Emerald", hex: "#10B981" }
    ]
  },
  {
    business: "Organic Cafe",
    industry: "Food & Beverage",
    style: "Warm & Inviting",
    palette: [
      { name: "Earth Brown", hex: "#8D5524" },
      { name: "Olive Green", hex: "#B2A972" },
      { name: "Sunflower", hex: "#FFD23F" },
      { name: "Cream", hex: "#FFF6E0" },
      { name: "Forest Green", hex: "#386641" },
      { name: "Coral", hex: "#F76E11" },
      { name: "Clay", hex: "#C97D60" },
      { name: "Sprout", hex: "#B7E4C7" }
    ]
  },
  {
    business: "Law Firm",
    industry: "Finance",
    style: "Elegant",
    palette: [
      { name: "Navy Blue", hex: "#1A237E" },
      { name: "Gold", hex: "#FFD700" },
      { name: "Slate", hex: "#6C757D" },
      { name: "Pearl", hex: "#F5F5F5" },
      { name: "Midnight", hex: "#22223B" },
      { name: "Steel", hex: "#7B8FA1" },
      { name: "Sand", hex: "#E5C07B" },
      { name: "Verdant", hex: "#43AA8B" }
    ]
  },
  {
    business: "Kids Clothing Brand",
    industry: "Fashion & Beauty",
    style: "Playful",
    palette: [
      { name: "Bubblegum Pink", hex: "#FF6F91" },
      { name: "Lemon Zest", hex: "#FFD166" },
      { name: "Mint Green", hex: "#06D6A0" },
      { name: "Sky Blue", hex: "#4ECDC4" },
      { name: "Lavender", hex: "#B388FF" },
      { name: "Tangerine", hex: "#FF9F1C" },
      { name: "Powder Blue", hex: "#B5EAEA" },
      { name: "White", hex: "#FFFFFF" }
    ]
  },
  {
    business: "Yoga Studio",
    industry: "Wellness",
    style: "Minimalist",
    palette: [
      { name: "Stone", hex: "#A8A8A8" },
      { name: "Cloud", hex: "#E5E5E5" },
      { name: "Leaf", hex: "#9BC53D" },
      { name: "Sand", hex: "#F6E7CB" },
      { name: "Ocean", hex: "#3A506B" },
      { name: "Rose", hex: "#E07A5F" },
      { name: "Mist", hex: "#B7C9E2" },
      { name: "Earth", hex: "#8D5524" }
    ]
  }
];

const ExamplesPage = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 to-indigo-950 text-white">
      {/* Navbar */}
      <nav className="border-b border-slate-800 bg-slate-900/95 backdrop-blur-md sticky top-0 z-20">
        <div className="max-w-7xl mx-auto px-4 flex justify-between items-center h-16">
          <Link to="/" className="text-2xl font-bold bg-gradient-to-r from-indigo-400 to-purple-400 bg-clip-text text-transparent">
            PaletteAI
          </Link>
          <Link to="/" className="text-slate-300 hover:text-white transition-colors">
            ← Home
          </Link>
        </div>
      </nav>

      <div className="max-w-5xl mx-auto px-4 py-12">
        <h1 className="text-4xl font-bold mb-8 text-center bg-gradient-to-r from-indigo-400 to-purple-400 bg-clip-text text-transparent">
          Palette Examples
        </h1>
        <p className="text-slate-300 text-center mb-12 max-w-2xl mx-auto">
          Explore some sample palettes generated by PaletteAI for different industries, businesses, and styles.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
          {EXAMPLES.map((example, idx) => (
            <div key={idx} className="bg-slate-800/60 rounded-2xl p-6 border border-slate-700/50 shadow-lg hover:shadow-indigo-500/10 transition-all">
              <div className="mb-4 flex flex-wrap gap-2">
                {example.palette.map((color, cidx) => (
                  <div key={cidx} className="flex flex-col items-center">
                    <div
                      className="w-10 h-10 rounded-lg shadow"
                      style={{ backgroundColor: color.hex }}
                      title={color.name}
                    />
                    <span className="text-xs mt-1 text-slate-200 font-semibold" style={{
                      maxWidth: "70px",
                      whiteSpace: "nowrap",
                      overflow: "hidden",
                      textOverflow: "ellipsis"
                    }}>
                      {color.name}
                    </span>
                    <span className="text-[10px] text-slate-400 font-mono">{color.hex}</span>
                  </div>
                ))}
              </div>
              <div>
                <h2 className="text-xl font-bold text-indigo-300 mb-1">{example.business}</h2>
                <div className="flex flex-wrap gap-2 mb-2">
                  <span className="bg-indigo-700/40 text-indigo-200 px-2 py-1 rounded text-xs font-semibold">{example.industry}</span>
                  <span className="bg-purple-700/40 text-purple-200 px-2 py-1 rounded text-xs font-semibold">{example.style}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
        <div className="text-center mt-12">
          <Link
            to="/create"
            className="inline-block px-8 py-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl font-semibold hover:from-indigo-700 hover:to-purple-700 transition-all duration-200 shadow-lg hover:scale-105"
          >
            Generate Your Own Palette
          </Link>
        </div>
      </div>
    </div>
  );
};

export default ExamplesPage;
